networks:
  app-network:
    driver: bridge
    name: app-network

services:
  db:
    image: mongo:7.0.14
    container_name: db
    networks:
      - app-network
    ports:
      - "4000:27017"
    restart: always

  rabbitmq:
    image: rabbitmq:4.0.0-management-alpine
    container_name: rabbitmq
    networks:
      - app-network
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: "always"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.dev
    container_name: video-streaming
    volumes:
      - ./video-streaming/src:/usr/src/app/src
      - ./video-streaming/videos:/usr/src/app/videos
    networks:
      - app-network
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - RABBITMQ=amqp://guest:guest@rabbitmq:5672
      - NODE_ENV=development
    depends_on:
      - rabbitmq
    restart: "no"
  
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile.dev
    container_name: history
    volumes:
      - ./history/src:/usr/src/app/src
    networks:
      - app-network
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBITMQ=amqp://guest:guest@rabbitmq:5672
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
      - rabbitmq
    restart: "no"
