FROM oven/bun:1.1.27-alpine

WORKDIR /usr/src/app

COPY package.json bun.lockb ./
RUN bun install

COPY tsconfig.json ./
COPY ./src ./src
COPY ./videos ./videos

EXPOSE 80/tcp

CMD bunx wait-on -i 10000 -v tcp:rabbitmq:5672 && bun dev
