services:
  db:
    image: mongo:7.0.14
    container_name: db
    ports:
      - "4000:27017"
    restart: always

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile.dev
    container_name: video-streaming
    volumes:
      - ./video-streaming/src:/usr/src/app/src
      - ./video-streaming/videos:/usr/src/app/videos
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
    restart: "no"
  
  history:
    image: history
    build:
      context: ./history
      dockerfile: Dockerfile.dev
    container_name: history
    volumes:
      - ./history/src:/usr/src/app/src
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - NODE_ENV=development
    depends_on:
      - db
    restart: "no"
