name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: |
          cd chapter_08/example-2
          bun install

      - name: Run Tests
        run: |
          cd chapter_08/example-2
          bun test:unit
